# Generated by Django 4.0.1 on 2022-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
